# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:08
from __future__ import unicode_literals

import boardinghouse.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSchema',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demo_schema', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expires_at', models.DateTimeField()),
            ],
            bases=(boardinghouse.base.SharedSchemaMixin, models.Model),
        ),
    ]
