# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 02:36
from __future__ import unicode_literals

import boardinghouse.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSchema',
            fields=[
                ('template_schema_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'template schemata',
                'default_permissions': ('add', 'change', 'delete', 'view', 'activate', 'clone'),
            },
            bases=(boardinghouse.base.SharedSchemaMixin, models.Model),
        ),
    ]
