# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:40
from __future__ import unicode_literals

import boardinghouse.base
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField()),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(0, b'Summer Semester'), (1, b'Semester 1'), (2, b'Semester 2')])),
                ('grade', models.CharField(blank=True, choices=[(b'HD', b'High Distinction'), (b'D', b'Distinction'), (b'C', b'Credit'), (b'P1', b'Pass, Level 1'), (b'P2', b'Pass, Level 2'), (b'F1', b'Fail, Level 1'), (b'F2', b'Fail, Level 2'), (b'NGP', b'Non-Graded Pass'), (b'NGF', b'Non-Graded Fail')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schema', models.CharField(help_text='The internal name of the schema.<br>May only contain lowercase letters, digits and underscores. Must start with a letter.<br>May not be changed after creation.', max_length=36, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='May only contain lowercase letters, digits and underscores. Must start with a letter.', regex=b'^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(help_text='The display name of the schema.', max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Use this instead of deleting schemata.')),
            ],
            options={
                'abstract': False,
            },
            bases=(boardinghouse.base.SharedSchemaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('staff_id', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('student_id', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='school.Student'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='school.Subject'),
        ),
    ]
